spring.application.name=gpsserver
spring.datasource.url=jdbc:mysql://x.y.z.w:3306/gpsdb
spring.datasource.username=abc
spring.datasource.password=abc
// completare informatii conexiune la baza de date
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
